version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels: ["dependencies"]
    versioning-strategy: increase-if-necessary

    # group dependencies by type
    groups:
      security:
        applies-to: security-updates
      regular:
        applies-to: version-updates
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
