export default defineAppConfig({
  social: [
    { link: 'https://www.instagram.com', icon: 'uil:instagram', name: 'Instagram' },
    { link: 'https://www.facebook.com', icon: 'uil:facebook-f', name: 'Facebook' },
    { link: 'https://www.linkedin.com', icon: 'uil:linkedin-alt', name: 'LinkedIn' },
  ],
  contacts: [
    { icon: 'material-symbols:call-sharp', title: 'Fale Conosco', content: '+55 (17) 99746-8333' },
    { icon: 'uil:search', title: 'Nosso Email', content: 'contato@brickhomecenter.com.br' },
    { icon: 'material-symbols:alarm', title: 'Horário de Funcionamento', content: 'Seg - Sex: 09h - 19h' },
    { icon: 'material-symbols:map', title: 'Localização', content: 'Rua Descida, 1712, Centro - Jales - SP' },
  ],
  services: [
    {
      id: 1,
      image_1: 'Foto de um caminhão de entrega de materiais de construção saindo da frente da loja, carregado com pallets de cimento e blocos.',
      title: 'Entrega Programada de Materiais',
      description_1: 'A entrega programada de materiais permite que você receba tudo o que precisa exatamente na fase certa da obra, evitando desperdícios e falta de insumos.',
      description_2: 'Você agenda o dia e o horário das entregas e nossa equipe organiza a logística para que cimento, areia, blocos, ferragens e outros materiais cheguem com segurança e pontualidade no seu canteiro.',
      image_2: 'Close de um colaborador conferindo a nota de entrega junto ao cliente na obra, com materiais descarregando ao fundo.',
      subtitle: 'Mais organização e menos atraso na obra',
      description_3: 'Com a entrega programada, você reduz o risco de parada da obra por falta de material, otimiza o espaço de armazenamento e ganha mais controle sobre o cronograma. É a forma mais prática de manter sua construção andando no ritmo certo.',
    },
    {
      id: 2,
      image_1: 'Pessoa em uma mesa com planta de obra aberta, calculadora e amostras de materiais, simulando um orçamento.',
      title: 'Orçamento e Lista de Materiais',
      description_1: 'Montamos uma lista completa de materiais para a sua obra, de acordo com o projeto e com o padrão de acabamento que você deseja.',
      description_2: 'Nossa equipe ajuda a transformar o seu projeto em uma lista organizada com quantidades estimadas, tipos de produtos e sugestões de alternativas para caber no seu orçamento.',
      image_2: 'Tela de computador exibindo um orçamento detalhado, com um vendedor explicando ao cliente ao lado do balcão.',
      subtitle: 'Planejamento que cabe no seu bolso',
      description_3: 'Com um bom orçamento e uma lista bem feita, você evita compras desnecessárias, consegue comparar opções de preço e mantém o controle dos gastos da obra do início ao fim.',
    },
    {
      id: 3,
      image_1: 'Foto de um técnico com capacete e prancheta dentro de uma obra em andamento, avaliando paredes e estrutura.',
      title: 'Atendimento Técnico na Obra',
      description_1: 'Disponibilizamos atendimento técnico para orientar na escolha dos materiais ideais para cada etapa da construção.',
      description_2: 'Nosso time pode visitar sua obra ou atender à distância para esclarecer dúvidas sobre aplicação de produtos, compatibilidade de materiais e melhores soluções para o seu tipo de projeto.',
      image_2: 'Técnico conversando com o mestre de obras ao lado de pilhas de blocos, cimento e ferragens.',
      subtitle: 'Acompanhamento especializado para decisões mais seguras',
      description_3: 'Com suporte técnico, você reduz retrabalho, evita erros de especificação e garante que os materiais certos sejam aplicados da forma correta, aumentando a durabilidade e a segurança da construção.',
    },
    {
      id: 4,
      date: '20 de novembro de 2025',
      image_1: 'Máquina de serra circular em uma marcenaria cortando peças de madeira, com um colaborador operando o equipamento.',
      title: 'Corte e Beneficiamento de Madeiras',
      description_1: 'Oferecemos serviço de corte e beneficiamento de madeiras sob medida para uso em telhados, forros, decks e outras estruturas.',
      description_2: 'Você escolhe o tipo de madeira e informa as medidas desejadas, e nossa equipe realiza cortes precisos, escuadria e preparação das peças para facilitar a montagem na obra.',
      image_2: 'Peças de madeira já cortadas, empilhadas e etiquetadas prontas para entrega ao cliente.',
      subtitle: 'Praticidade e precisão na montagem',
      description_3: 'Com as madeiras já cortadas e preparadas, a montagem fica mais rápida, há menos desperdício e a obra ganha em qualidade e acabamento, principalmente em telhados e estruturas aparentes.',
    },
    {
      id: 5,
      image_1: 'Balcão de tintas com diversas latas coloridas e uma máquina de mistura de tintas ao fundo.',
      title: 'Mistura e Personalização de Tintas',
      description_1: 'Criamos a cor perfeita para o seu projeto através de máquinas de mistura computadorizadas, garantindo tonalidades fiéis e repetíveis.',
      description_2: 'Você pode trazer uma referência de cor ou escolher em nossos catálogos, e preparamos a tinta na hora, no tipo certo para cada ambiente: interno, externo, piso, fachada e muito mais.',
      image_2: 'Close de um funcionário abrindo uma lata de tinta recém-misturada, com a cor sendo conferida em um cartão de teste.',
      subtitle: 'Cores que combinam com o seu estilo',
      description_3: 'A personalização de tintas permite que sua obra tenha identidade própria, com cores pensadas para cada ambiente. Além disso, mantemos o registro da fórmula para que você possa repetir a mesma cor no futuro.',
    },
    {
      id: 6,
      image_1: 'Exposição de ferramentas elétricas e equipamentos de construção, como martelete, betoneira e compactador, organizados em um setor de locação.',
      title: 'Locação de Ferramentas e Equipamentos',
      description_1: 'Para quem não quer comprar tudo, oferecemos locação de ferramentas e equipamentos que agilizam a execução da obra.',
      description_2: 'Disponibilizamos itens como marteletes, lixadeiras, furadeiras, betoneiras, andaimes e outros equipamentos, sempre revisados e prontos para uso.',
      image_2: 'Cliente recebendo um equipamento alugado de um atendente, com termo de locação sendo assinado.',
      subtitle: 'Economia sem perder produtividade',
      description_3: 'Alugar é uma forma inteligente de ter acesso a ferramentas profissionais sem precisar investir alto na compra. Você utiliza o equipamento pelo tempo necessário, reduz custos e mantém a obra andando no ritmo ideal.',
    },
  ],
  blog: [
    {
      id: 1,
      date: '23 NOV',
      image_1: '/images/blog/item/1/blog-1.jpg',
      title: 'Como Planejar a Reforma da Sua Casa Sem Dor de Cabeça',
      description_1: 'Antes de começar qualquer reforma, o planejamento é o passo mais importante. Definir o objetivo da obra, o orçamento disponível e o prazo desejado ajuda a evitar surpresas ao longo do processo.',
      description_2: 'Uma boa prática é listar todos os ambientes que serão reformados, o que precisa ser feito em cada um e quais materiais serão necessários. Assim, você consegue comparar preços, avaliar opções de qualidade e montar um cronograma realista junto com os profissionais.',
      image_2: '/images/blog/item/1/blog-2.jpg',
      subtitle: 'Organização e escolha certa de materiais',
      description_3: 'Centralizar as compras em uma loja de material de construção de confiança facilita o controle dos custos e a logística de entrega. Além disso, contar com orientação especializada na hora de escolher tintas, pisos, argamassas e demais itens garante um resultado melhor e mais duradouro.',
    },
    {
      id: 2,
      date: '22 NOV',
      image_1: '/images/blog/item/2/blog-1.jpg',
      title: 'Qual Piso Escolher para Cada Ambiente da Casa',
      description_1: 'Sala, cozinha, banheiro e área externa pedem pisos com características diferentes. Entender essas diferenças é essencial para não errar na escolha e garantir conforto, beleza e resistência no dia a dia.',
      description_2: 'Ambientes úmidos, como banheiro e lavanderia, pedem revestimentos antiderrapantes e fáceis de limpar. Já salas e quartos podem receber pisos mais aconchegantes, como laminados ou vinílicos, que oferecem conforto térmico e acústico.',
      image_2: '/images/blog/item/2/blog-2.jpg',
      subtitle: 'Durabilidade, praticidade e estilo',
      description_3: 'Antes de comprar, avalie o tráfego de pessoas em cada ambiente, o estilo da decoração e o nível de manutenção que você está disposto a ter. Uma boa loja de materiais oferece opções de pisos para todos os perfis, além de indicar argamassas e rejuntes adequados para cada tipo de revestimento.',
    },
    {
      id: 3,
      date: '21 NOV',
      image_1: '/images/blog/item/3/blog-1.jpg',
      title: 'Cimento, Argamassa e Rejunte: Entenda as Diferenças na Prática',
      description_1: 'Apesar de estarem sempre juntos nas obras, cimento, argamassa e rejunte têm funções bem diferentes. Saber para que serve cada um é importante para evitar desperdícios e problemas estruturais ou de acabamento.',
      description_2: 'O cimento é a base de muitas misturas, usado em concretos e contrapiso. A argamassa é o produto pronto (ou quase pronto) usado para assentar pisos e revestimentos. Já o rejunte é aplicado entre as peças, garantindo vedação e acabamento.',
      image_2: '/images/blog/item/3/blog-2.jpg',
      subtitle: 'Escolha certa para um acabamento perfeito',
      description_3: 'Na hora de comprar, observe se o produto é indicado para áreas internas ou externas, se resiste à umidade e ao tráfego intenso e se é compatível com o tipo de revestimento escolhido. Uma orientação rápida no balcão da loja pode evitar retrabalho e garantir um resultado profissional.',
    }, {
      id: 4,
      date: '20 NOV',
      image_1: '/images/blog/item/4/blog-1.jpg',
      title: 'Kit Básico de Ferramentas que Não Pode Faltar em Casa',
      description_1: 'Mesmo quem não é profissional da construção se beneficia de ter um kit básico de ferramentas em casa. Pequenos reparos, instalações simples e ajustes do dia a dia ficam muito mais fáceis quando você tem os itens certos à mão.',
      description_2: 'Entre os indispensáveis estão: martelo, chaves de fenda e Phillips, alicate, trena, nível, furadeira e alguns parafusos e buchas de tamanhos variados. Com esse conjunto, já dá para resolver boa parte das demandas domésticas.',
      image_2: '/images/blog/item/4/blog-2.jpg',
      subtitle: 'Mais autonomia para pequenos reparos',
      description_3: 'Muitas lojas de material de construção oferecem kits prontos, pensados justamente para o uso residencial. Além disso, é possível ir montando o seu conjunto aos poucos, investindo em ferramentas de melhor qualidade conforme a necessidade cresce.',
    },
    {
      id: 5,
      date: '19 NOV',
      image_1: '/images/blog/item/5/blog-1.jpg',
      title: 'Tendências em Acabamentos para Deixar sua Obra Mais Moderna',
      description_1: 'Os acabamentos são responsáveis por grande parte da personalidade de um projeto. Tintas, revestimentos, metais e iluminação transformam a sensação dos ambientes e podem valorizar muito o imóvel.',
      description_2: 'Entre as tendências atuais estão tons neutros combinados com pontos de cor, revestimentos que imitam madeira ou pedra, metais em preto ou dourado e o uso estratégico de iluminação em LED para destacar detalhes da arquitetura.',
      image_2: '/images/blog/item/5/blog-2.jpg',
      subtitle: 'Detalhes que fazem diferença no resultado final',
      description_3: 'Na hora de escolher os acabamentos, é importante equilibrar estilo e praticidade. Produtos de boa procedência, com garantia e indicação clara de uso, evitam problemas como manchas, infiltrações e desgaste precoce. Uma loja especializada pode ajudar a combinar materiais e cores para alcançar o visual que você deseja.',
    },
  ],
})
